#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MYSQL
#    username: sa
#    password:
#  sql:
#    init:
#      schema-locations:
#        - classpath:db/table.sql
#      data-locations:
#        - classpath:db/data.sql
logging:
  level:
    root: off